FROM alpine:3.23

LABEL maintainer="atmoz.net"
LABEL org.opencontainers.image.description="Secure SFTP server based on OpenSSH (Alpine)"

# Steps done in one RUN layer:
# - Install upgrades and new packages
# - OpenSSH needs /var/run/sshd to run
# - Remove generic host keys, entrypoint generates unique keys
RUN apk update && apk upgrade && \
    apk add --no-cache bash shadow openssh-server-pam openssh-sftp-server && \
    ln -s /usr/sbin/sshd.pam /usr/sbin/sshd && \
    mkdir -p /var/run/sshd && \
    rm -f /etc/ssh/ssh_host_*key*

COPY files/sshd_config /etc/ssh/sshd_config
COPY files/create-sftp-user /usr/local/bin/
COPY files/entrypoint /

HEALTHCHECK --interval=30s --timeout=5s --retries=3 \
    CMD pgrep sshd > /dev/null || exit 1

EXPOSE 22

ENTRYPOINT ["/entrypoint"]
