name: Push image
on:
  workflow_call:
    inputs:
      containerfile:
        description: Which containerfile/dockerfile to build
        required: true
        type: string
      image:
        description: image name
        required: true
        type: string
      tag:
        description: image tag
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build image
        run: |
          docker build . \
            --pull=true \
            --file="${{ inputs.containerfile }}" \
            --tag="${{ inputs.image }}:${{ inputs.tag }}" \
            --label="org.opencontainers.image.source=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" \
            --label="org.opencontainers.image.revision=$GITHUB_SHA" \
            --label="org.opencontainers.image.created=$(date --rfc-3339=seconds)"

      - name: Test image
        run: tests/run "${{ inputs.image }}:${{ inputs.tag }}"
        env:
          CONTAINER_ENGINE: docker

      - name: Push image to Docker Hub
        if: github.ref == 'refs/heads/master'
        run: |
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login \
            -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

          docker push "${{ inputs.image }}:${{ inputs.tag }}"
          docker logout
