name: build

on:
  push:
    paths-ignore:
      - "*.md"
      - "*.txt"
      - "*.png"
  pull_request:
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          ignore_paths: tests/shunit2

  alpine:
    needs: verify
    uses: ./.github/workflows/build-image.yml
    with:
      containerfile: Dockerfile-alpine
      image: maduonline/easy-sftp
      tag: alpine
    secrets: inherit

  debian:
    needs: verify
    uses: ./.github/workflows/build-image.yml
    with:
      containerfile: Dockerfile
      image: maduonline/easy-sftp
      tag: debian
    secrets: inherit
